# Generated by Django 5.1.6 on 2025-02-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0002_alter_timeentry_duration_alter_timeentry_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id_device',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
