# Generated by Django 5.1.6 on 2025-02-23 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0002_alter_timeentry_duration_alter_timeentry_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
