# Generated by Django 5.1.6 on 2025-02-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0003_remove_user_device_id_user_id_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
